{
  "name": "Unrar Monitor",
  "version": "1.16",
  "slug": "unrar_monitor",
  "description": "Monitora e extrai arquivos .rar automaticamente no Home Assistant",
  "startup": "application",
  "boot": "auto",
  "homeassistant": "2023.0.0",
  "arch": ["amd64", "armv7", "aarch64"],

  "init": false,
  "host_network": true,
  "usb": false,

  "full_access": true,
  "privileged": [
    "SYS_ADMIN"
  ],

  "map": [
    "config:rw",
    "addons:rw",
    "ssl:rw",
    "backup:rw",
    "share:rw",
    "media:rw"
  ],

  "options": {},
  "schema": {}
}
