{
  "name": "Script Startup",
  "version": "1.1",
  "slug": "meu_addon_teste",
  "description": "Addon de teste criado por Murilo",
  "startup": "application",
  "boot": "auto",
  "homeassistant": "2023.0.0",
  "arch": ["amd64", "armv7", "aarch64"],
  "options": {},
  "schema": {},
  "init": false,
  "privileged": [
    "SYS_ADMIN",
    "DAC_READ_SEARCH",
    "SYS_RAWIO"
  ],
  "host_network": true
  "map": [
    "config:rw",
    "addons:rw",
    "ssl:rw",
    "backup:rw",
    "share:rw",
    "media:rw"
  ]
}



