{
  "name": "Script Startup",
  "version": "1.6",
  "slug": "script_startup",
  "description": "Add-on de teste criado por Murilo",
  "startup": "application",
  "boot": "auto",
  "homeassistant": "2023.0.0",
  "arch": ["amd64", "armv7", "aarch64"],
  "init": false,
  "privileged": true,
  "host_network": true,
  "map": ["all"],
  "full_access": true,
  "usb": true,
  "options": {},
  "schema": {}
}