{
  "name": "Script Startup",
  "version": "1.16",
  "slug": "script_startup",
  "description": "Scripts de Inicialização Home Assistant",
  "startup": "application",
  "boot": "auto",
  "homeassistant": "2023.0.0",
  "arch": ["amd64", "armv7", "aarch64"],
  "options": {},
  "schema": {},
  "init": false,
  "privileged": [
    "SYS_ADMIN"
  ],
  "host_network": true,
  "map": [
    "config:rw",
    "addons:rw",
    "ssl:rw",
    "backup:rw",
    "share:rw",
    "media:rw",
    "data:rw"
  ],
  "full_access": true, 
  "usb": true
} 
